-- HospitalRun 3 — consolidated deploy script
-- GENERATED by scripts/build-deploy-sql.sh — do not edit by hand.
--
-- Paste this into the Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- and click Run. See DEPLOY.md for the full walkthrough.
--
-- Re-running is safe: the guard below raises a clear error and rolls back
-- the transaction if the schema is already applied. No partial writes.
--
-- Sources (in order):
--   00001_initial_schema.sql
--   00002_rls_policies.sql
--   00003_jwt_claims.sql
--   00004_schema_enhancements.sql
--   00005_v2_parity.sql
--   00006_grant_authenticated.sql
--   00007_imaging_storage.sql
--   00008_jwt_hook_grants.sql
--   00009_bootstrap_user_rpc.sql
--   00010_own_profile_select.sql
--   00011_org_admin_update.sql
--   00012_org_members.sql
--   00013_visit_scoping.sql
--   00014_invited_user_hint.sql
--   00015_schema_meta.sql
--   00016_schema_version_rpc.sql

begin;

-- Guard: if schema_meta exists and version >= 1, abort cleanly.
do $guard$
begin
  if exists (
    select 1 from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'schema_meta'
  ) and exists (select 1 from public.schema_meta where version >= 1) then
    raise exception 'HospitalRun schema is already at version % — no changes made. This is expected when re-running deploy.sql.', (select max(version) from public.schema_meta)
      using hint = 'If you intended to upgrade the schema, run the new migrations via the Supabase CLI.';
  end if;
end
$guard$;

-- >>> 00001_initial_schema.sql
-- HospitalRun 3 — Initial Database Schema
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New Query)

-- ============================================================
-- Organizations
-- ============================================================
create table organizations (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  slug        text not null unique,
  created_at  timestamptz not null default now()
);

-- ============================================================
-- Profiles (extends auth.users)
-- ============================================================
create table profiles (
  id          uuid primary key references auth.users on delete cascade,
  org_id      uuid not null references organizations on delete cascade,
  role        text not null default 'user' check (role in ('admin', 'user', 'nurse', 'doctor')),
  full_name   text not null,
  created_at  timestamptz not null default now()
);

create index idx_profiles_org_id on profiles (org_id);

-- ============================================================
-- Patients
-- ============================================================
create table patients (
  id                  uuid primary key default gen_random_uuid(),
  org_id              uuid not null references organizations on delete cascade,
  mrn                 text,
  prefix              text,
  given_name          text not null,
  family_name         text not null,
  suffix              text,
  date_of_birth       date,
  sex                 text check (sex in ('male', 'female', 'other', 'unknown')),
  blood_type          text,
  occupation          text,
  preferred_language  text,
  phone               text,
  email               text,
  address             jsonb,
  status              text not null default 'active' check (status in ('active', 'inactive', 'deceased')),
  deleted_at          timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index idx_patients_org_id on patients (org_id);
create index idx_patients_mrn on patients (org_id, mrn);
create index idx_patients_name on patients (org_id, family_name, given_name);

-- ============================================================
-- Visits
-- ============================================================
create table visits (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  type            text,
  status          text not null default 'planned' check (status in ('planned', 'in-progress', 'finished', 'cancelled')),
  reason          text,
  start_datetime  timestamptz,
  end_datetime    timestamptz,
  notes           text,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_visits_org_patient on visits (org_id, patient_id);

-- ============================================================
-- Appointments
-- ============================================================
create table appointments (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  type            text,
  start_time      timestamptz not null,
  end_time        timestamptz not null,
  location        text,
  requested_by    uuid references profiles,
  status          text not null default 'scheduled' check (status in ('scheduled', 'completed', 'cancelled', 'no-show')),
  notes           text,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_appointments_org on appointments (org_id);
create index idx_appointments_patient on appointments (org_id, patient_id);
create index idx_appointments_time on appointments (org_id, start_time);

-- ============================================================
-- Labs
-- ============================================================
create table labs (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  visit_id        uuid references visits,
  code            text,
  type            text not null,
  status          text not null default 'requested' check (status in ('requested', 'completed', 'canceled')),
  requested_by    uuid references profiles,
  requested_at    timestamptz not null default now(),
  completed_at    timestamptz,
  canceled_at     timestamptz,
  result          text,
  notes           text,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_labs_org on labs (org_id);
create index idx_labs_patient on labs (org_id, patient_id);

-- ============================================================
-- Medications
-- ============================================================
create table medications (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  visit_id        uuid references visits,
  name            text not null,
  status          text not null default 'draft' check (status in ('draft', 'active', 'on hold', 'canceled', 'completed', 'entered in error', 'stopped', 'unknown')),
  intent          text,
  priority        text,
  quantity        text,
  requested_by    uuid references profiles,
  start_date      date,
  end_date        date,
  notes           text,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_medications_org on medications (org_id);
create index idx_medications_patient on medications (org_id, patient_id);

-- ============================================================
-- Incidents
-- ============================================================
create table incidents (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  reported_by     uuid references profiles,
  reported_on     timestamptz not null default now(),
  patient_id      uuid references patients on delete set null,
  department      text,
  category        text,
  category_item   text,
  description     text not null,
  status          text not null default 'reported' check (status in ('reported', 'resolved')),
  resolved_on     timestamptz,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_incidents_org on incidents (org_id);

-- ============================================================
-- Imaging
-- ============================================================
create table imaging (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  visit_id        uuid references visits,
  code            text,
  type            text not null,
  status          text not null default 'requested' check (status in ('requested', 'completed', 'canceled')),
  requested_by    uuid references profiles,
  requested_on    timestamptz not null default now(),
  completed_on    timestamptz,
  canceled_on     timestamptz,
  notes           text,
  storage_path    text,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_imaging_org on imaging (org_id);
create index idx_imaging_patient on imaging (org_id, patient_id);

-- ============================================================
-- Diagnoses
-- ============================================================
create table diagnoses (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  icd_code        text,
  description     text not null,
  diagnosed_at    timestamptz,
  diagnosed_by    uuid references profiles,
  notes           text,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_diagnoses_org_patient on diagnoses (org_id, patient_id);

-- ============================================================
-- Allergies
-- ============================================================
create table allergies (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  allergen        text not null,
  reaction        text,
  severity        text check (severity in ('mild', 'moderate', 'severe')),
  noted_at        timestamptz,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_allergies_org_patient on allergies (org_id, patient_id);

-- ============================================================
-- Notes (clinical)
-- ============================================================
create table notes (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  content         text not null,
  author_id       uuid references profiles,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_notes_org_patient on notes (org_id, patient_id);

-- ============================================================
-- Related Persons (emergency contacts / family)
-- ============================================================
create table related_persons (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  given_name      text not null,
  family_name     text not null,
  relationship    text,
  phone           text,
  email           text,
  address         jsonb,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_related_persons_org_patient on related_persons (org_id, patient_id);

-- ============================================================
-- Care Goals
-- ============================================================
create table care_goals (
  id                  uuid primary key default gen_random_uuid(),
  org_id              uuid not null references organizations on delete cascade,
  patient_id          uuid not null references patients on delete cascade,
  description         text not null,
  start_date          date,
  target_date         date,
  achievement_status  text default 'in-progress' check (achievement_status in ('in-progress', 'improving', 'not-achieving', 'sustaining', 'achieved', 'not-attainable')),
  priority            text check (priority in ('low', 'medium', 'high')),
  notes               text,
  deleted_at          timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index idx_care_goals_org_patient on care_goals (org_id, patient_id);

-- ============================================================
-- Care Plans
-- ============================================================
create table care_plans (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references organizations on delete cascade,
  patient_id      uuid not null references patients on delete cascade,
  title           text not null,
  description     text,
  start_date      date,
  end_date        date,
  status          text not null default 'draft' check (status in ('draft', 'active', 'on-hold', 'revoked', 'completed', 'entered-in-error', 'unknown')),
  notes           text,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_care_plans_org_patient on care_plans (org_id, patient_id);

-- ============================================================
-- Patient History (append-only audit log)
-- ============================================================
create table patient_history (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references organizations on delete cascade,
  patient_id  uuid not null references patients on delete cascade,
  changed_by  uuid references profiles,
  changed_at  timestamptz not null default now(),
  field_name  text not null,
  old_value   text,
  new_value   text
);

create index idx_patient_history_org_patient on patient_history (org_id, patient_id);
create index idx_patient_history_changed_at on patient_history (patient_id, changed_at desc);

-- ============================================================
-- Updated_at trigger function
-- ============================================================
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Apply updated_at triggers
create trigger trg_patients_updated_at before update on patients for each row execute function update_updated_at();
create trigger trg_visits_updated_at before update on visits for each row execute function update_updated_at();
create trigger trg_appointments_updated_at before update on appointments for each row execute function update_updated_at();
create trigger trg_labs_updated_at before update on labs for each row execute function update_updated_at();
create trigger trg_medications_updated_at before update on medications for each row execute function update_updated_at();
create trigger trg_incidents_updated_at before update on incidents for each row execute function update_updated_at();
create trigger trg_imaging_updated_at before update on imaging for each row execute function update_updated_at();
create trigger trg_diagnoses_updated_at before update on diagnoses for each row execute function update_updated_at();
create trigger trg_allergies_updated_at before update on allergies for each row execute function update_updated_at();
create trigger trg_notes_updated_at before update on notes for each row execute function update_updated_at();
create trigger trg_related_persons_updated_at before update on related_persons for each row execute function update_updated_at();
create trigger trg_care_goals_updated_at before update on care_goals for each row execute function update_updated_at();
create trigger trg_care_plans_updated_at before update on care_plans for each row execute function update_updated_at();

-- >>> 00002_rls_policies.sql
-- HospitalRun 3 — Row Level Security
-- Run this AFTER 00001_initial_schema.sql

-- ============================================================
-- Helper: extract org_id from the JWT
-- ============================================================
-- Supabase blocks creating functions in the auth schema from the SQL Editor.
-- This function lives in public instead; behaviour is identical.
create or replace function public.org_id()
returns uuid as $$
  select coalesce(
    (auth.jwt() -> 'app_metadata' ->> 'org_id')::uuid,
    (select org_id from profiles where id = auth.uid())
  );
$$ language sql stable security definer;

-- ============================================================
-- Enable RLS on every table
-- ============================================================
alter table organizations    enable row level security;
alter table profiles         enable row level security;
alter table patients         enable row level security;
alter table visits           enable row level security;
alter table appointments     enable row level security;
alter table labs             enable row level security;
alter table medications      enable row level security;
alter table incidents        enable row level security;
alter table imaging          enable row level security;
alter table diagnoses        enable row level security;
alter table allergies        enable row level security;
alter table notes            enable row level security;
alter table related_persons  enable row level security;
alter table care_goals       enable row level security;
alter table care_plans       enable row level security;
alter table patient_history  enable row level security;

-- ============================================================
-- Organizations — users can only see their own org
-- ============================================================
create policy "Users can view own org"
  on organizations for select
  using (id = public.org_id());

-- ============================================================
-- Profiles — users in the same org can see each other
-- ============================================================
create policy "Users can view org profiles"
  on profiles for select
  using (org_id = public.org_id());

create policy "Users can update own profile"
  on profiles for update
  using (id = auth.uid());

-- ============================================================
-- Org-scoped tables: same policy pattern for all
-- Users can SELECT, INSERT, UPDATE rows in their org.
-- Deletes are soft (set deleted_at), no hard delete via client.
-- ============================================================

-- Macro: apply org-scoped policies to a table
-- (Postgres doesn't have macros, so we repeat the pattern)

-- Patients
create policy "Org isolation select" on patients for select using (org_id = public.org_id());
create policy "Org isolation insert" on patients for insert with check (org_id = public.org_id());
create policy "Org isolation update" on patients for update using (org_id = public.org_id());

-- Visits
create policy "Org isolation select" on visits for select using (org_id = public.org_id());
create policy "Org isolation insert" on visits for insert with check (org_id = public.org_id());
create policy "Org isolation update" on visits for update using (org_id = public.org_id());

-- Appointments
create policy "Org isolation select" on appointments for select using (org_id = public.org_id());
create policy "Org isolation insert" on appointments for insert with check (org_id = public.org_id());
create policy "Org isolation update" on appointments for update using (org_id = public.org_id());

-- Labs
create policy "Org isolation select" on labs for select using (org_id = public.org_id());
create policy "Org isolation insert" on labs for insert with check (org_id = public.org_id());
create policy "Org isolation update" on labs for update using (org_id = public.org_id());

-- Medications
create policy "Org isolation select" on medications for select using (org_id = public.org_id());
create policy "Org isolation insert" on medications for insert with check (org_id = public.org_id());
create policy "Org isolation update" on medications for update using (org_id = public.org_id());

-- Incidents
create policy "Org isolation select" on incidents for select using (org_id = public.org_id());
create policy "Org isolation insert" on incidents for insert with check (org_id = public.org_id());
create policy "Org isolation update" on incidents for update using (org_id = public.org_id());

-- Imaging
create policy "Org isolation select" on imaging for select using (org_id = public.org_id());
create policy "Org isolation insert" on imaging for insert with check (org_id = public.org_id());
create policy "Org isolation update" on imaging for update using (org_id = public.org_id());

-- Diagnoses
create policy "Org isolation select" on diagnoses for select using (org_id = public.org_id());
create policy "Org isolation insert" on diagnoses for insert with check (org_id = public.org_id());
create policy "Org isolation update" on diagnoses for update using (org_id = public.org_id());

-- Allergies
create policy "Org isolation select" on allergies for select using (org_id = public.org_id());
create policy "Org isolation insert" on allergies for insert with check (org_id = public.org_id());
create policy "Org isolation update" on allergies for update using (org_id = public.org_id());

-- Notes
create policy "Org isolation select" on notes for select using (org_id = public.org_id());
create policy "Org isolation insert" on notes for insert with check (org_id = public.org_id());
create policy "Org isolation update" on notes for update using (org_id = public.org_id());

-- Related Persons
create policy "Org isolation select" on related_persons for select using (org_id = public.org_id());
create policy "Org isolation insert" on related_persons for insert with check (org_id = public.org_id());
create policy "Org isolation update" on related_persons for update using (org_id = public.org_id());

-- Care Goals
create policy "Org isolation select" on care_goals for select using (org_id = public.org_id());
create policy "Org isolation insert" on care_goals for insert with check (org_id = public.org_id());
create policy "Org isolation update" on care_goals for update using (org_id = public.org_id());

-- Care Plans
create policy "Org isolation select" on care_plans for select using (org_id = public.org_id());
create policy "Org isolation insert" on care_plans for insert with check (org_id = public.org_id());
create policy "Org isolation update" on care_plans for update using (org_id = public.org_id());

-- Patient History (read-only for clients — inserts happen via trigger/server)
create policy "Org isolation select" on patient_history for select using (org_id = public.org_id());
create policy "Org isolation insert" on patient_history for insert with check (org_id = public.org_id());

-- >>> 00003_jwt_claims.sql
-- HospitalRun 3 — Custom JWT Claims
-- Injects org_id and role into the JWT via app_metadata so RLS can read them.

-- ============================================================
-- Hook: on every sign-in, copy org_id + role from profiles → JWT
-- This uses Supabase's custom access token hook pattern.
-- ============================================================

-- Function that Supabase calls to customize the JWT
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  claims jsonb;
  user_org_id uuid;
  user_role text;
begin
  -- Get org_id and role from the profiles table
  select org_id, role into user_org_id, user_role
    from profiles
    where id = (event ->> 'user_id')::uuid;

  -- Get existing claims
  claims := event -> 'claims';

  -- If the user has a profile, inject org_id and role
  if user_org_id is not null then
    claims := jsonb_set(claims, '{app_metadata}',
      coalesce(claims -> 'app_metadata', '{}'::jsonb) ||
      jsonb_build_object('org_id', user_org_id, 'role', user_role)
    );
    event := jsonb_set(event, '{claims}', claims);
  end if;

  return event;
end;
$$;

-- Grant execute to supabase_auth_admin so the hook can be called
grant execute on function public.custom_access_token_hook to supabase_auth_admin;

-- Revoke from public
revoke execute on function public.custom_access_token_hook from public;
revoke execute on function public.custom_access_token_hook from anon;
revoke execute on function public.custom_access_token_hook from authenticated;

-- ============================================================
-- Helper: seed a test org + user profile after sign-up
-- Auto-creates an org and profile when a new user signs up,
-- if they don't already have one.
-- ============================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_org_id uuid;
begin
  -- Check if user already has a profile
  if exists (select 1 from profiles where id = new.id) then
    return new;
  end if;

  -- Create a default organization for the user
  insert into organizations (name, slug)
    values (
      coalesce(new.raw_user_meta_data ->> 'org_name', 'My Hospital'),
      coalesce(new.raw_user_meta_data ->> 'org_slug', 'org-' || substr(new.id::text, 1, 8))
    )
    returning id into new_org_id;

  -- Create the user's profile
  insert into profiles (id, org_id, role, full_name)
    values (
      new.id,
      new_org_id,
      'admin',
      coalesce(new.raw_user_meta_data ->> 'full_name', new.email)
    );

  return new;
end;
$$;

-- Trigger on auth.users
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- >>> 00004_schema_enhancements.sql
-- Migration 00004: Schema enhancements for v2 feature parity
-- Adds fields to diagnoses, care_goals, visits, and care_plans

-- Diagnosis: add status, onset_date, abatement_date
ALTER TABLE diagnoses ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE diagnoses ADD COLUMN IF NOT EXISTS onset_date date;
ALTER TABLE diagnoses ADD COLUMN IF NOT EXISTS abatement_date date;

-- Care Goal: add status field
ALTER TABLE care_goals ADD COLUMN IF NOT EXISTS status text;

-- Visit: add location field
ALTER TABLE visits ADD COLUMN IF NOT EXISTS location text;

-- Care Plan: add intent field
ALTER TABLE care_plans ADD COLUMN IF NOT EXISTS intent text;

-- >>> 00005_v2_parity.sql
-- Migration: v2 feature parity additions
-- Adds fields needed to close functional gaps between v2 and v3.

-- Patients: support for approximate/unknown date of birth
ALTER TABLE patients
  ADD COLUMN IF NOT EXISTS is_approximate_date_of_birth boolean DEFAULT false;

-- Care plans: link a care plan to a specific diagnosis
ALTER TABLE care_plans
  ADD COLUMN IF NOT EXISTS diagnosis_id uuid REFERENCES diagnoses(id) ON DELETE SET NULL;

-- Appointments: separate reason-for-visit field (distinct from clinical notes)
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS reason text;

-- >>> 00006_grant_authenticated.sql
-- HospitalRun 3 — Grant table privileges to the authenticated role
--
-- The initial schema migration created tables but did not grant any
-- table-level privileges to the `authenticated` role. PostgREST runs every
-- request as `authenticated` after JWT validation, so without these grants
-- every query returns 42501 "permission denied for table X" *before*
-- RLS policies are even evaluated.

grant usage on schema public to authenticated;

grant select, insert, update, delete on
  organizations,
  profiles,
  patients,
  visits,
  appointments,
  labs,
  medications,
  incidents,
  imaging,
  diagnoses,
  allergies,
  notes,
  related_persons,
  care_goals,
  care_plans,
  patient_history
to authenticated;

-- Sequences (none in current schema, but make defaults safe for the future)
grant usage, select on all sequences in schema public to authenticated;

-- Make sure tables created later in this schema also inherit the grants
alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;

alter default privileges in schema public
  grant usage, select on sequences to authenticated;

-- >>> 00007_imaging_storage.sql
-- HospitalRun 3 — Imaging Storage bucket + org-scoped RLS
-- Run AFTER 00006_grant_authenticated.sql

-- ============================================================
-- Private bucket for imaging files
-- ============================================================
insert into storage.buckets (id, name, public)
values ('imaging', 'imaging', false)
on conflict (id) do nothing;

-- ============================================================
-- RLS on storage.objects for the imaging bucket.
-- Path convention: {org_id}/{imaging_id}/{filename}
-- Users can only touch files whose first path segment matches their org_id.
-- ============================================================
create policy "imaging: read own org files"
  on storage.objects for select
  using (
    bucket_id = 'imaging'
    and (storage.foldername(name))[1] = public.org_id()::text
  );

create policy "imaging: insert own org files"
  on storage.objects for insert
  with check (
    bucket_id = 'imaging'
    and (storage.foldername(name))[1] = public.org_id()::text
    and auth.uid() = owner
  );

create policy "imaging: update own org files"
  on storage.objects for update
  using (
    bucket_id = 'imaging'
    and (storage.foldername(name))[1] = public.org_id()::text
  )
  with check (
    bucket_id = 'imaging'
    and (storage.foldername(name))[1] = public.org_id()::text
  );

create policy "imaging: delete own org files"
  on storage.objects for delete
  using (
    bucket_id = 'imaging'
    and (storage.foldername(name))[1] = public.org_id()::text
  );

-- >>> 00008_jwt_hook_grants.sql
-- Allow the custom_access_token_hook (run as supabase_auth_admin) to
-- read the profiles table. Without this, the hook raises a permission
-- error on every token issuance and the client's getSession()/refresh
-- call fails, leaving the app stuck in isLoading.

grant usage on schema public to supabase_auth_admin;
grant select on public.profiles to supabase_auth_admin;

-- RLS policy: permit supabase_auth_admin to read any profile (it only
-- runs server-side inside the Auth hook, never as an end user).
drop policy if exists "auth_admin_read_profiles" on public.profiles;
create policy "auth_admin_read_profiles"
  on public.profiles
  as permissive
  for select
  to supabase_auth_admin
  using (true);

-- >>> 00009_bootstrap_user_rpc.sql
-- RPC that lets a signed-in user create an org + profile for themselves
-- on demand. Runs as SECURITY DEFINER so it bypasses the INSERT-less RLS
-- on organizations and profiles. Idempotent: if the caller already has a
-- profile, returns the existing org_id without changes.

create or replace function public.bootstrap_current_user(
  org_name text default 'My Hospital'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  existing_org uuid;
  new_org_id uuid;
  user_email text;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  select org_id into existing_org from profiles where id = uid;
  if existing_org is not null then
    return existing_org;
  end if;

  select email into user_email from auth.users where id = uid;

  insert into organizations (name, slug)
    values (
      org_name,
      'org-' || substr(uid::text, 1, 8)
    )
    returning id into new_org_id;

  insert into profiles (id, org_id, role, full_name)
    values (
      uid,
      new_org_id,
      'admin',
      coalesce(user_email, 'Admin')
    );

  return new_org_id;
end;
$$;

grant execute on function public.bootstrap_current_user(text) to authenticated;

-- >>> 00010_own_profile_select.sql
-- Allow any authenticated user to always read their own profile row,
-- even when their org_id is not yet populated. The existing
-- "Users can view org profiles" policy requires the caller's own
-- org_id to match, which is a chicken-and-egg problem for users who
-- don't have a profile yet.

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
  on public.profiles
  for select
  using (id = auth.uid());

-- >>> 00011_org_admin_update.sql
-- Allow admins of an org to UPDATE that org's row (rename, etc).
-- Existing policy only covered SELECT, so admin renames silently fail.

drop policy if exists "Admins can update own org" on public.organizations;
create policy "Admins can update own org"
  on public.organizations
  for update
  using (
    id = public.org_id()
    and exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  )
  with check (
    id = public.org_id()
  );

-- >>> 00012_org_members.sql
-- org_members: tracks pending + accepted invitations into an organization.
-- Accepted members are mirrored into `profiles` by the invite-member Edge Function.

create table if not exists public.org_members (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  role text not null check (role in ('admin', 'doctor', 'nurse', 'user')),
  invited_email text not null,
  invited_by uuid references auth.users(id) on delete set null,
  invited_at timestamptz not null default now(),
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists org_members_org_email_idx
  on public.org_members (org_id, lower(invited_email));

create index if not exists org_members_user_idx on public.org_members (user_id);

alter table public.org_members enable row level security;

-- Only admins of the same org can see or modify invitations.
create policy "org_members_admin_select"
  on public.org_members
  for select
  to authenticated
  using (
    org_id = coalesce(
      (auth.jwt() ->> 'org_id')::uuid,
      (select p.org_id from public.profiles p where p.id = auth.uid())
    )
    and (
      (auth.jwt() ->> 'role') = 'admin'
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.role = 'admin' and p.org_id = org_members.org_id
      )
    )
  );

create policy "org_members_admin_insert"
  on public.org_members
  for insert
  to authenticated
  with check (
    org_id = coalesce(
      (auth.jwt() ->> 'org_id')::uuid,
      (select p.org_id from public.profiles p where p.id = auth.uid())
    )
    and (
      (auth.jwt() ->> 'role') = 'admin'
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.role = 'admin' and p.org_id = org_members.org_id
      )
    )
  );

create policy "org_members_admin_update"
  on public.org_members
  for update
  to authenticated
  using (
    (auth.jwt() ->> 'role') = 'admin'
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin' and p.org_id = org_members.org_id
    )
  )
  with check (
    (auth.jwt() ->> 'role') = 'admin'
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin' and p.org_id = org_members.org_id
    )
  );

create policy "org_members_admin_delete"
  on public.org_members
  for delete
  to authenticated
  using (
    (auth.jwt() ->> 'role') = 'admin'
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin' and p.org_id = org_members.org_id
    )
  );

-- Self-select: a user can see their own pending invite by email match.
create policy "org_members_self_select"
  on public.org_members
  for select
  to authenticated
  using (
    user_id = auth.uid()
    or lower(invited_email) = lower((auth.jwt() ->> 'email'))
  );

grant select, insert, update, delete on public.org_members to authenticated;

-- >>> 00013_visit_scoping.sql
-- Stage 6: scope diagnoses and notes to visits (episodes of care).
-- Labs, medications, imaging already have visit_id from earlier migrations.

alter table public.diagnoses
  add column if not exists visit_id uuid references public.visits(id) on delete set null;

alter table public.notes
  add column if not exists visit_id uuid references public.visits(id) on delete set null;

create index if not exists diagnoses_visit_id_idx on public.diagnoses (visit_id);
create index if not exists notes_visit_id_idx on public.notes (visit_id);

-- >>> 00014_invited_user_hint.sql
-- HospitalRun 3 — Invited-user hint for handle_new_user
--
-- When an admin creates a user via the invite-member edge function
-- (mode: 'create'), we want the new auth.users row to be attached to
-- the admin's existing org — NOT to spawn a fresh one. Extend
-- handle_new_user() to honor `invited_org_id` + `invited_role` hints
-- placed in raw_user_meta_data.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_org_id uuid;
  invited_org uuid;
  invited_role text;
begin
  if exists (select 1 from profiles where id = new.id) then
    return new;
  end if;

  invited_org := nullif(new.raw_user_meta_data ->> 'invited_org_id', '')::uuid;
  invited_role := nullif(new.raw_user_meta_data ->> 'invited_role', '');

  if invited_org is not null and exists (select 1 from organizations where id = invited_org) then
    insert into profiles (id, org_id, role, full_name)
      values (
        new.id,
        invited_org,
        coalesce(invited_role, 'user'),
        coalesce(new.raw_user_meta_data ->> 'full_name', new.email)
      );
    return new;
  end if;

  -- Fallback: self-signup path — spawn a new org for this user.
  insert into organizations (name, slug)
    values (
      coalesce(new.raw_user_meta_data ->> 'org_name', 'My Hospital'),
      coalesce(new.raw_user_meta_data ->> 'org_slug', 'org-' || substr(new.id::text, 1, 8))
    )
    returning id into new_org_id;

  insert into profiles (id, org_id, role, full_name)
    values (
      new.id,
      new_org_id,
      'admin',
      coalesce(new.raw_user_meta_data ->> 'full_name', new.email)
    );

  return new;
end;
$$;

-- >>> 00015_schema_meta.sql
-- HospitalRun 3 — Schema version tracking
--
-- One-row-per-version table used by both the developer flow
-- (supabase db push) and the browser-only deploy flow (pasting
-- supabase/deploy.sql into the SQL Editor) to detect whether the
-- schema has already been applied and to drive the in-app
-- "upgrade required" guard.

create table if not exists public.schema_meta (
  version int primary key,
  applied_at timestamptz not null default now()
);

alter table public.schema_meta enable row level security;

-- Everyone authenticated can read the current version — the frontend
-- uses it for the schema-version guard. Nothing sensitive here.
drop policy if exists schema_meta_select on public.schema_meta;
create policy schema_meta_select on public.schema_meta
  for select
  to authenticated
  using (true);

-- Writes are service-role only (via migrations or deploy.sql).
-- No insert/update/delete policy for authenticated = deny by default.

insert into public.schema_meta (version) values (1)
  on conflict (version) do nothing;

-- >>> 00016_schema_version_rpc.sql
-- HospitalRun 3 — Schema version RPC
--
-- Exposes the current schema version to authenticated clients so the
-- frontend can detect a stale-DB-vs-new-frontend mismatch and show
-- the "Upgrade required" screen with a pointer to DEPLOY.md.

create or replace function public.current_schema_version()
returns int
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(max(version), 0) from public.schema_meta;
$$;

grant execute on function public.current_schema_version() to authenticated;

commit;

-- end of deploy.sql
