#!/usr/bin/env bash
# Build supabase/deploy.sql by concatenating supabase/migrations/*.sql in
# order, wrapped in a transaction gated on public.schema_meta so a
# second paste into the Supabase SQL Editor aborts cleanly instead of
# erroring partway through with "relation already exists".
#
# The output is committed to the repo. CI runs this and fails the build
# if `git diff --exit-code supabase/deploy.sql` is nonempty, so migration
# changes never ship without a matching deploy.sql bump.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
MIGRATIONS_DIR="$ROOT/supabase/migrations"
OUT="$ROOT/supabase/deploy.sql"

if [[ ! -d "$MIGRATIONS_DIR" ]]; then
  echo "error: $MIGRATIONS_DIR not found" >&2
  exit 1
fi

shopt -s nullglob
migrations=("$MIGRATIONS_DIR"/*.sql)
shopt -u nullglob

if (( ${#migrations[@]} == 0 )); then
  echo "error: no migrations found in $MIGRATIONS_DIR" >&2
  exit 1
fi

IFS=$'\n' migrations=($(printf '%s\n' "${migrations[@]}" | sort))
unset IFS

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "-- HospitalRun 3 — consolidated deploy script"
  echo "-- GENERATED by scripts/build-deploy-sql.sh — do not edit by hand."
  echo "--"
  echo "-- Paste this into the Supabase SQL Editor (Dashboard → SQL Editor → New Query)"
  echo "-- and click Run. See DEPLOY.md for the full walkthrough."
  echo "--"
  echo "-- Re-running is safe: the guard below raises a clear error and rolls back"
  echo "-- the transaction if the schema is already applied. No partial writes."
  echo "--"
  echo "-- Sources (in order):"
  for m in "${migrations[@]}"; do
    echo "--   $(basename "$m")"
  done
  echo
  echo "begin;"
  echo
  echo "-- Guard: if schema_meta exists and version >= 1, abort cleanly."
  echo "do \$guard\$"
  echo "begin"
  echo "  if exists ("
  echo "    select 1 from pg_class c"
  echo "    join pg_namespace n on n.oid = c.relnamespace"
  echo "    where n.nspname = 'public' and c.relname = 'schema_meta'"
  echo "  ) and exists (select 1 from public.schema_meta where version >= 1) then"
  echo "    raise exception 'HospitalRun schema is already at version % — no changes made. This is expected when re-running deploy.sql.', (select max(version) from public.schema_meta)"
  echo "      using hint = 'If you intended to upgrade the schema, run the new migrations via the Supabase CLI.';"
  echo "  end if;"
  echo "end"
  echo "\$guard\$;"
  echo

  for m in "${migrations[@]}"; do
    name="$(basename "$m")"
    echo "-- >>> $name"
    # Strip trailing blank lines but preserve interior formatting.
    awk 'NF {for(i=0;i<blank;i++) print ""; blank=0; print; next} {blank++}' "$m"
    echo
  done

  echo "commit;"
  echo
  echo "-- end of deploy.sql"
} > "$tmp"

mv "$tmp" "$OUT"
trap - EXIT

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
