/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthPatientsIndexRouteImport } from './routes/_auth/patients/index'
import { Route as AuthMedicationsIndexRouteImport } from './routes/_auth/medications/index'
import { Route as AuthLabsIndexRouteImport } from './routes/_auth/labs/index'
import { Route as AuthIncidentsIndexRouteImport } from './routes/_auth/incidents/index'
import { Route as AuthImagingIndexRouteImport } from './routes/_auth/imaging/index'
import { Route as AuthAppointmentsIndexRouteImport } from './routes/_auth/appointments/index'
import { Route as AuthVisitsVisitIdRouteImport } from './routes/_auth/visits/$visitId'
import { Route as AuthPatientsNewRouteImport } from './routes/_auth/patients/new'
import { Route as AuthPatientsPatientIdRouteImport } from './routes/_auth/patients/$patientId'
import { Route as AuthMedicationsNewRouteImport } from './routes/_auth/medications/new'
import { Route as AuthMedicationsMedicationIdRouteImport } from './routes/_auth/medications/$medicationId'
import { Route as AuthLabsNewRouteImport } from './routes/_auth/labs/new'
import { Route as AuthLabsLabIdRouteImport } from './routes/_auth/labs/$labId'
import { Route as AuthIncidentsVisualizeRouteImport } from './routes/_auth/incidents/visualize'
import { Route as AuthIncidentsNewRouteImport } from './routes/_auth/incidents/new'
import { Route as AuthIncidentsIncidentIdRouteImport } from './routes/_auth/incidents/$incidentId'
import { Route as AuthImagingNewRouteImport } from './routes/_auth/imaging/new'
import { Route as AuthImagingImagingIdRouteImport } from './routes/_auth/imaging/$imagingId'
import { Route as AuthAppointmentsNewRouteImport } from './routes/_auth/appointments/new'
import { Route as AuthAppointmentsCalendarRouteImport } from './routes/_auth/appointments/calendar'
import { Route as AuthAppointmentsAppointmentIdRouteImport } from './routes/_auth/appointments/$appointmentId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsIndexRoute = AuthPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMedicationsIndexRoute = AuthMedicationsIndexRouteImport.update({
  id: '/medications/',
  path: '/medications/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLabsIndexRoute = AuthLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIncidentsIndexRoute = AuthIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImagingIndexRoute = AuthImagingIndexRouteImport.update({
  id: '/imaging/',
  path: '/imaging/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppointmentsIndexRoute = AuthAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVisitsVisitIdRoute = AuthVisitsVisitIdRouteImport.update({
  id: '/visits/$visitId',
  path: '/visits/$visitId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsNewRoute = AuthPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsPatientIdRoute = AuthPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMedicationsNewRoute = AuthMedicationsNewRouteImport.update({
  id: '/medications/new',
  path: '/medications/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMedicationsMedicationIdRoute =
  AuthMedicationsMedicationIdRouteImport.update({
    id: '/medications/$medicationId',
    path: '/medications/$medicationId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthLabsNewRoute = AuthLabsNewRouteImport.update({
  id: '/labs/new',
  path: '/labs/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLabsLabIdRoute = AuthLabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIncidentsVisualizeRoute = AuthIncidentsVisualizeRouteImport.update({
  id: '/incidents/visualize',
  path: '/incidents/visualize',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIncidentsNewRoute = AuthIncidentsNewRouteImport.update({
  id: '/incidents/new',
  path: '/incidents/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIncidentsIncidentIdRoute = AuthIncidentsIncidentIdRouteImport.update({
  id: '/incidents/$incidentId',
  path: '/incidents/$incidentId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImagingNewRoute = AuthImagingNewRouteImport.update({
  id: '/imaging/new',
  path: '/imaging/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImagingImagingIdRoute = AuthImagingImagingIdRouteImport.update({
  id: '/imaging/$imagingId',
  path: '/imaging/$imagingId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppointmentsNewRoute = AuthAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppointmentsCalendarRoute =
  AuthAppointmentsCalendarRouteImport.update({
    id: '/appointments/calendar',
    path: '/appointments/calendar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAppointmentsAppointmentIdRoute =
  AuthAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/appointments/$appointmentId': typeof AuthAppointmentsAppointmentIdRoute
  '/appointments/calendar': typeof AuthAppointmentsCalendarRoute
  '/appointments/new': typeof AuthAppointmentsNewRoute
  '/imaging/$imagingId': typeof AuthImagingImagingIdRoute
  '/imaging/new': typeof AuthImagingNewRoute
  '/incidents/$incidentId': typeof AuthIncidentsIncidentIdRoute
  '/incidents/new': typeof AuthIncidentsNewRoute
  '/incidents/visualize': typeof AuthIncidentsVisualizeRoute
  '/labs/$labId': typeof AuthLabsLabIdRoute
  '/labs/new': typeof AuthLabsNewRoute
  '/medications/$medicationId': typeof AuthMedicationsMedicationIdRoute
  '/medications/new': typeof AuthMedicationsNewRoute
  '/patients/$patientId': typeof AuthPatientsPatientIdRoute
  '/patients/new': typeof AuthPatientsNewRoute
  '/visits/$visitId': typeof AuthVisitsVisitIdRoute
  '/appointments/': typeof AuthAppointmentsIndexRoute
  '/imaging/': typeof AuthImagingIndexRoute
  '/incidents/': typeof AuthIncidentsIndexRoute
  '/labs/': typeof AuthLabsIndexRoute
  '/medications/': typeof AuthMedicationsIndexRoute
  '/patients/': typeof AuthPatientsIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/': typeof AuthIndexRoute
  '/appointments/$appointmentId': typeof AuthAppointmentsAppointmentIdRoute
  '/appointments/calendar': typeof AuthAppointmentsCalendarRoute
  '/appointments/new': typeof AuthAppointmentsNewRoute
  '/imaging/$imagingId': typeof AuthImagingImagingIdRoute
  '/imaging/new': typeof AuthImagingNewRoute
  '/incidents/$incidentId': typeof AuthIncidentsIncidentIdRoute
  '/incidents/new': typeof AuthIncidentsNewRoute
  '/incidents/visualize': typeof AuthIncidentsVisualizeRoute
  '/labs/$labId': typeof AuthLabsLabIdRoute
  '/labs/new': typeof AuthLabsNewRoute
  '/medications/$medicationId': typeof AuthMedicationsMedicationIdRoute
  '/medications/new': typeof AuthMedicationsNewRoute
  '/patients/$patientId': typeof AuthPatientsPatientIdRoute
  '/patients/new': typeof AuthPatientsNewRoute
  '/visits/$visitId': typeof AuthVisitsVisitIdRoute
  '/appointments': typeof AuthAppointmentsIndexRoute
  '/imaging': typeof AuthImagingIndexRoute
  '/incidents': typeof AuthIncidentsIndexRoute
  '/labs': typeof AuthLabsIndexRoute
  '/medications': typeof AuthMedicationsIndexRoute
  '/patients': typeof AuthPatientsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/appointments/$appointmentId': typeof AuthAppointmentsAppointmentIdRoute
  '/_auth/appointments/calendar': typeof AuthAppointmentsCalendarRoute
  '/_auth/appointments/new': typeof AuthAppointmentsNewRoute
  '/_auth/imaging/$imagingId': typeof AuthImagingImagingIdRoute
  '/_auth/imaging/new': typeof AuthImagingNewRoute
  '/_auth/incidents/$incidentId': typeof AuthIncidentsIncidentIdRoute
  '/_auth/incidents/new': typeof AuthIncidentsNewRoute
  '/_auth/incidents/visualize': typeof AuthIncidentsVisualizeRoute
  '/_auth/labs/$labId': typeof AuthLabsLabIdRoute
  '/_auth/labs/new': typeof AuthLabsNewRoute
  '/_auth/medications/$medicationId': typeof AuthMedicationsMedicationIdRoute
  '/_auth/medications/new': typeof AuthMedicationsNewRoute
  '/_auth/patients/$patientId': typeof AuthPatientsPatientIdRoute
  '/_auth/patients/new': typeof AuthPatientsNewRoute
  '/_auth/visits/$visitId': typeof AuthVisitsVisitIdRoute
  '/_auth/appointments/': typeof AuthAppointmentsIndexRoute
  '/_auth/imaging/': typeof AuthImagingIndexRoute
  '/_auth/incidents/': typeof AuthIncidentsIndexRoute
  '/_auth/labs/': typeof AuthLabsIndexRoute
  '/_auth/medications/': typeof AuthMedicationsIndexRoute
  '/_auth/patients/': typeof AuthPatientsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/appointments/$appointmentId'
    | '/appointments/calendar'
    | '/appointments/new'
    | '/imaging/$imagingId'
    | '/imaging/new'
    | '/incidents/$incidentId'
    | '/incidents/new'
    | '/incidents/visualize'
    | '/labs/$labId'
    | '/labs/new'
    | '/medications/$medicationId'
    | '/medications/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/visits/$visitId'
    | '/appointments/'
    | '/imaging/'
    | '/incidents/'
    | '/labs/'
    | '/medications/'
    | '/patients/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/'
    | '/appointments/$appointmentId'
    | '/appointments/calendar'
    | '/appointments/new'
    | '/imaging/$imagingId'
    | '/imaging/new'
    | '/incidents/$incidentId'
    | '/incidents/new'
    | '/incidents/visualize'
    | '/labs/$labId'
    | '/labs/new'
    | '/medications/$medicationId'
    | '/medications/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/visits/$visitId'
    | '/appointments'
    | '/imaging'
    | '/incidents'
    | '/labs'
    | '/medications'
    | '/patients'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/setup'
    | '/_auth/'
    | '/_auth/appointments/$appointmentId'
    | '/_auth/appointments/calendar'
    | '/_auth/appointments/new'
    | '/_auth/imaging/$imagingId'
    | '/_auth/imaging/new'
    | '/_auth/incidents/$incidentId'
    | '/_auth/incidents/new'
    | '/_auth/incidents/visualize'
    | '/_auth/labs/$labId'
    | '/_auth/labs/new'
    | '/_auth/medications/$medicationId'
    | '/_auth/medications/new'
    | '/_auth/patients/$patientId'
    | '/_auth/patients/new'
    | '/_auth/visits/$visitId'
    | '/_auth/appointments/'
    | '/_auth/imaging/'
    | '/_auth/incidents/'
    | '/_auth/labs/'
    | '/_auth/medications/'
    | '/_auth/patients/'
    | '/_auth/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients/': {
      id: '/_auth/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthPatientsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/medications/': {
      id: '/_auth/medications/'
      path: '/medications'
      fullPath: '/medications/'
      preLoaderRoute: typeof AuthMedicationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/labs/': {
      id: '/_auth/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof AuthLabsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/incidents/': {
      id: '/_auth/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthIncidentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/imaging/': {
      id: '/_auth/imaging/'
      path: '/imaging'
      fullPath: '/imaging/'
      preLoaderRoute: typeof AuthImagingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appointments/': {
      id: '/_auth/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthAppointmentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/visits/$visitId': {
      id: '/_auth/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof AuthVisitsVisitIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients/new': {
      id: '/_auth/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthPatientsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients/$patientId': {
      id: '/_auth/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthPatientsPatientIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/medications/new': {
      id: '/_auth/medications/new'
      path: '/medications/new'
      fullPath: '/medications/new'
      preLoaderRoute: typeof AuthMedicationsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/medications/$medicationId': {
      id: '/_auth/medications/$medicationId'
      path: '/medications/$medicationId'
      fullPath: '/medications/$medicationId'
      preLoaderRoute: typeof AuthMedicationsMedicationIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/labs/new': {
      id: '/_auth/labs/new'
      path: '/labs/new'
      fullPath: '/labs/new'
      preLoaderRoute: typeof AuthLabsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/labs/$labId': {
      id: '/_auth/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof AuthLabsLabIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/incidents/visualize': {
      id: '/_auth/incidents/visualize'
      path: '/incidents/visualize'
      fullPath: '/incidents/visualize'
      preLoaderRoute: typeof AuthIncidentsVisualizeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/incidents/new': {
      id: '/_auth/incidents/new'
      path: '/incidents/new'
      fullPath: '/incidents/new'
      preLoaderRoute: typeof AuthIncidentsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/incidents/$incidentId': {
      id: '/_auth/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AuthIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/imaging/new': {
      id: '/_auth/imaging/new'
      path: '/imaging/new'
      fullPath: '/imaging/new'
      preLoaderRoute: typeof AuthImagingNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/imaging/$imagingId': {
      id: '/_auth/imaging/$imagingId'
      path: '/imaging/$imagingId'
      fullPath: '/imaging/$imagingId'
      preLoaderRoute: typeof AuthImagingImagingIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appointments/new': {
      id: '/_auth/appointments/new'
      path: '/appointments/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AuthAppointmentsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appointments/calendar': {
      id: '/_auth/appointments/calendar'
      path: '/appointments/calendar'
      fullPath: '/appointments/calendar'
      preLoaderRoute: typeof AuthAppointmentsCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appointments/$appointmentId': {
      id: '/_auth/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AuthAppointmentsAppointmentIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAppointmentsAppointmentIdRoute: typeof AuthAppointmentsAppointmentIdRoute
  AuthAppointmentsCalendarRoute: typeof AuthAppointmentsCalendarRoute
  AuthAppointmentsNewRoute: typeof AuthAppointmentsNewRoute
  AuthImagingImagingIdRoute: typeof AuthImagingImagingIdRoute
  AuthImagingNewRoute: typeof AuthImagingNewRoute
  AuthIncidentsIncidentIdRoute: typeof AuthIncidentsIncidentIdRoute
  AuthIncidentsNewRoute: typeof AuthIncidentsNewRoute
  AuthIncidentsVisualizeRoute: typeof AuthIncidentsVisualizeRoute
  AuthLabsLabIdRoute: typeof AuthLabsLabIdRoute
  AuthLabsNewRoute: typeof AuthLabsNewRoute
  AuthMedicationsMedicationIdRoute: typeof AuthMedicationsMedicationIdRoute
  AuthMedicationsNewRoute: typeof AuthMedicationsNewRoute
  AuthPatientsPatientIdRoute: typeof AuthPatientsPatientIdRoute
  AuthPatientsNewRoute: typeof AuthPatientsNewRoute
  AuthVisitsVisitIdRoute: typeof AuthVisitsVisitIdRoute
  AuthAppointmentsIndexRoute: typeof AuthAppointmentsIndexRoute
  AuthImagingIndexRoute: typeof AuthImagingIndexRoute
  AuthIncidentsIndexRoute: typeof AuthIncidentsIndexRoute
  AuthLabsIndexRoute: typeof AuthLabsIndexRoute
  AuthMedicationsIndexRoute: typeof AuthMedicationsIndexRoute
  AuthPatientsIndexRoute: typeof AuthPatientsIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAppointmentsAppointmentIdRoute: AuthAppointmentsAppointmentIdRoute,
  AuthAppointmentsCalendarRoute: AuthAppointmentsCalendarRoute,
  AuthAppointmentsNewRoute: AuthAppointmentsNewRoute,
  AuthImagingImagingIdRoute: AuthImagingImagingIdRoute,
  AuthImagingNewRoute: AuthImagingNewRoute,
  AuthIncidentsIncidentIdRoute: AuthIncidentsIncidentIdRoute,
  AuthIncidentsNewRoute: AuthIncidentsNewRoute,
  AuthIncidentsVisualizeRoute: AuthIncidentsVisualizeRoute,
  AuthLabsLabIdRoute: AuthLabsLabIdRoute,
  AuthLabsNewRoute: AuthLabsNewRoute,
  AuthMedicationsMedicationIdRoute: AuthMedicationsMedicationIdRoute,
  AuthMedicationsNewRoute: AuthMedicationsNewRoute,
  AuthPatientsPatientIdRoute: AuthPatientsPatientIdRoute,
  AuthPatientsNewRoute: AuthPatientsNewRoute,
  AuthVisitsVisitIdRoute: AuthVisitsVisitIdRoute,
  AuthAppointmentsIndexRoute: AuthAppointmentsIndexRoute,
  AuthImagingIndexRoute: AuthImagingIndexRoute,
  AuthIncidentsIndexRoute: AuthIncidentsIndexRoute,
  AuthLabsIndexRoute: AuthLabsIndexRoute,
  AuthMedicationsIndexRoute: AuthMedicationsIndexRoute,
  AuthPatientsIndexRoute: AuthPatientsIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
